### ISSUE TITLE
Cords and component dont get deleted when deleted

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#10] opened 2016-01-18 01:12 UTC
Has happened about twice so far on one project. After some time working with the project things don't get deleted. Component deletion prompt works but the deletion dose not. Patch cords also don't get deleted.

**Comment by maxdee** [comment] 2016-01-18 01:20
Saving closing and opening praxis does work.

**Comment by neilcsmith-net** [comment] 2016-01-18 11:01
Thanks for the report.  Are you using containers in this project?  I've noticed a bug recently with the first attempt to delete a container not working, although retrying does.  I need to look more fully into that, but not sure if you've got the same issue or something new.

Try closing and reopening the tab for the .pxr file - does this fix the issue too?  That would be a pointer to whether it's a bug on the editing side, or in the pipeline itself.

Is the project still running OK when this happens?  Have you got custom code in there?  I've also seen a similar problem occur if custom code causes a rendering error in Processing, but the visuals usually freeze in this case.

**Comment by maxdee** [comment] 2016-01-18 17:45
Using many containers. Will try closing/opening the tab next time the bug occurs. The project runs fine. Of course I have custom code :P

**Comment by neilcsmith-net** [comment] 2016-01-19 17:49
Of course you have custom code! ;-)  What I'm wondering is if it can definitely be replicated without custom coded components.  Anyway, if you can upload an example project that exhibits the issue, I'll take a look (or email privately if you don't want to share it).

**Comment by maxdee** [comment] 2016-01-21 01:34
So I left praxis_live open for about an hour mostly just sitting with this patch open and re-encountered the bug. Closing and reopening the graph editor did not do anything. Restarting the hub worked. I will send you my project.

**Comment by neilcsmith-net** [comment] 2016-01-21 17:06
Thanks for the project.  Your code is throwing a lot of exceptions (from `/videoXsession/pGrapher`) and I don't know whether this is partly the cause of the problem you're seeing.  Removing that component I still see the issue with having to delete a container twice to get it to delete (and now know the reason for that), but it seems to always delete on the second attempt.  It is actually deleted from the video pipeline on the first go.

The exceptions being thrown in that component are caused because you're accessing an ArrayList (data) using an input port before it is created in setup().  In any video component, setup() is not guaranteed to be called before any input ports - this is because setup() is delayed until the rendering cycle so you can call graphics methods like in Processing itself.  In fact, as this component isn't connected in the project you sent, setup() is never called and the Exception is being thrown on every frame.

It's better to get in the habit of initializing fields when defined, or using an initalizer (constructors aren't supported). That way, initializing data can be kept off the video thread too.

```java
private ArrayList<?> data;
{
  data = new ArrayList<>();
  // add some data if we want to
}
```
Hope that helps!

**Closed** 2016-03-17 10:27 UTC
Labels: bug, Minor
