### ISSUE TITLE
Service exited with abnormal code: 2

### ISSUE THREAD

**Issue by hesse2** [praxis-live/support#14] opened 2016-01-21 22:47 UTC
Getting this message in the console when I try running it on OS X 10.10:

com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000036.praxis_live[22923]) Service exited with abnormal code: 2

**Comment by neilcsmith-net** [comment] 2016-01-22 20:18
Thanks for the report. I think this is probably a duplicate of #9  Do you have a Java VM installed?

**Comment by neilcsmith-net** [comment] 2016-02-26 17:52
Closed due to lack of feedback.

**Closed by neilcsmith-net** 2016-02-26 17:52 UTC
Labels: waiting for feedback
