### ISSUE TITLE
saving p3d component crashes

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#36] opened 2016-06-19 19:17 UTC
Possibly related to NVIDIA drivers. Happened on xubuntu 16.04 and windows. The bug does not occur right away, possibly only when there is more then one p3d based component. Let me know if any specific tests need to happen!

[hs_err_pid3175.txt](https://github.com/praxis-live/support/files/322462/hs_err_pid3175.txt)

**Comment by maxdee** [comment] 2016-07-02 00:30
This also happens with version 2.3.1 as well as 2.3.2
deleting a p3d component crashes too...
Should I try another previous release?
[p3d_save_crash_praxis_2_3_1.txt](https://github.com/praxis-live/support/files/344337/p3d_save_crash_praxis_2_3_1.txt)

**Comment by neilcsmith-net** [comment] 2016-07-02 09:45
Thanks. That stack trace (I think) highlights where the issue is. When the code changes, the 3D PGraphics is disposed of at a time when we shouldn't be touching OpenGL.

https://github.com/praxis-live/praxis/blob/master/praxis.video.pgl.code/src/net/neilcsmith/praxis/video/pgl/code/P3DCodeContext.java#L108

My initial thoughts on keeping the 3D PGraphics between code changes should fix this. I'll probably look at a bug fix release for v2.3

**Comment by neilcsmith-net** [comment] 2016-07-02 16:15
@maxdee if you're up for testing your own build, try commenting out the following line (not same as above!) that calls p3d.dispose() -

https://github.com/praxis-live/praxis/blob/master/praxis.video.pgl.code/src/net/neilcsmith/praxis/video/pgl/code/P3DCodeContext.java#L192

This might be a useful quick fix for now (underlying Processing library should still handle the disposal at a later point), but will do some testing of that assumption ASAP.

**Comment by neilcsmith-net** [comment] 2016-07-03 10:57
Can you try the attached project. On my Intel card this works fine. With the Nvidia card it works fine on the first run, and consistently crashes once the hub has been restarted. This is all on Ubuntu 14.04.

If you can confirm similar on your system, I've got a fix for it that seems to be working here.

PS. This project is also a fun (but stupid) bit of meta-coding :smile: 

[NV_Crash.zip](https://github.com/praxis-live/support/files/344984/NV_Crash.zip)

**Comment by maxdee** [comment] 2016-07-05 22:47
It just crashed without even restarting the hub on my machine with nvidia card :/

**Comment by neilcsmith-net** [comment] 2016-07-07 14:00
Fixed in v2.3.3 (fingers X'd)

**Closed by neilcsmith-net** 2016-07-07 14:00 UTC
Labels: bug, Critical, waiting for feedback
