### ISSUE TITLE
Null Pointer Exception in SaveTask

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#17] opened 2016-01-27 16:34 UTC
Here is an annoying one I have encountered three times now. Unable to exit praxis-live, everything works fine, I just cant close the program. But then praxis does not close properly, work can be lost. So its kind of 2 problems, cant close praxis, cant really save work. Exporting the project might be a work around, I tried a few things with saving/exporting/killing and its not clear when the project actually gets saved.

**Comment by neilcsmith-net** [comment] 2016-01-27 17:24
Hi,

Thanks for the report.  Need a bit more information though!  ;-)  What exactly is lost?  Is this just that the *.pxp project file is missing files or empty, or something else?

If you can open the View / IDE log from the menu when this happens, can you send me it (right click, save as ...)

I've never seen this particular issue, except when something in native code throws a wobbly, but then that wouldn't count as everything working fine!  One protection against that is to run the video pipeline in a separate process - see https://praxisintermedia.wordpress.com/2014/11/06/distributed-hubs/ 

In terms of saving, each .pxr file can be saved individually at any point by saving from the patch window.  When you restart the hub or close the application you should have the option to save all .pxr files.  Custom code is not saved to disk until you save the .pxr file.  The project file .pxp which contains the list of .pxr files in the project is not saved until application shutdown - an issue which I think I've mentioned before and needs fixing.

Thanks, Neil

**Comment by maxdee** [comment] 2016-01-27 17:43
What I was losing was any modifications in the video patch during session that cant be closed properly. Mind you I mostly work in the video patch so I don't know about the other parts (gui/midi/osc). I restarted the hub when the problem occurred and I don't remember it asking to save my project and if it did, it did not work. Will send log next time!

So yeah the critical part is that the .pxp is only saved on proper application shutdown, which the bug prevents.

**Comment by neilcsmith-net** [comment] 2016-01-27 17:47
OK, thanks.  Hub restart should _always_ pop up a dialog to ask if you want to save.  If it doesn't, that's a bug!

You can add any missing files back into the .pxp file from the Properties menu item on the project.

**Comment by maxdee** [comment] 2016-01-28 16:07
Here is a log. I may have found out what causes the bug. When in this buggy state restarting the hub does not ask to save project.

[cant_close_bug_log_one.txt](https://github.com/praxis-live/support/files/108477/cant_close_bug_log_one.txt)

**Comment by maxdee** [comment] 2016-01-28 16:20
Not sure but the problem might be linked to:
Opening and running a project.
Opening a second project, building it to copy some custom components to paste into the first project.
Then deleting the second project's inactive hubs from the hub manager.

I cant quite reproduce the bug consistently, will report when figure more out.

**Comment by neilcsmith-net** [comment] 2016-01-28 16:40
Thanks for the log.  The NPE in SaveTask is odd, and might explain why shutdown fails.

If you can consistently prove that you've always done the above when you hit the bug, let me know.  There's a good chance that's the cause.  It looks like the SaveTask is trying to save a non-existent root.  I'll try and dig further and also look at making the SaveTask more robust in case of error.

Time for you to get your head around creating custom component files, and me to get my head around importing from a root file without building it! :wink:

**Comment by neilcsmith-net** [comment] 2016-10-02 09:37
Have noticed an edge case where there's still the possibility of an NPE during saving. This area will be revised more thoroughly in 3.1.

**Comment by neilcsmith-net** [comment] 2018-01-23 09:49
Cannot reproduce the NPE any more - seems underlying NB Platform changes may have stopped this happening since the original issue.  Going to close this for now - SaveTask will be looked at in v4 anyway.

**Closed by neilcsmith-net** 2018-01-23 09:49 UTC
Labels: Minor, bug
